# Generated by Django 4.1.5 on 2023-02-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='role',
            field=models.CharField(default='client', max_length=25),
        ),
    ]
