# Generated by Django 4.1.5 on 2023-02-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfood_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfood',
            name='role',
        ),
    ]
