# Generated by Django 4.1.5 on 2023-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price_cart',
            field=models.FloatField(blank=True),
        ),
    ]
