# Generated by Django 4.1.5 on 2023-01-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_food_category'),
        ('cart', '0002_alter_cart_total_price_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='food',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='food.food'),
        ),
    ]
