# Generated by Django 4.1.5 on 2023-01-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_food_remove_order_cart_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_order',
        ),
    ]
