# Generated by Django 4.1.5 on 2023-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_user_order_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_order',
            new_name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
