# Generated by Django 4.1.5 on 2023-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_cart_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_sending',
            field=models.BooleanField(default=False),
        ),
    ]
