# Generated by Django 4.1.5 on 2023-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_order_total_price_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_foods',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
