# Generated by Django 4.1.5 on 2023-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('cover', models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')),
                ('description', models.CharField(max_length=65)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('discount_perc', models.IntegerField()),
                ('is_discount', models.BooleanField(default=False)),
            ],
        ),
    ]
