# Generated by Django 4.1.5 on 2023-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price_discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount_perc',
            field=models.IntegerField(null=True),
        ),
    ]
