# Generated by Django 4.1.5 on 2023-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_price_discount_alter_food_discount_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount_perc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
