# Generated by Django 4.1.5 on 2023-01-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_discount_perc_alter_food_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
