# Generated by Django 4.1.5 on 2023-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='price_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
