# Generated by Django 4.1.5 on 2023-01-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cover',
            field=models.ImageField(upload_to='food/covers/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
