# Generated by Django 4.1.5 on 2023-01-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_alter_food_cover_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='food.category'),
        ),
    ]
