# Generated by Django 4.1.5 on 2023-01-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_alter_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price_discount',
        ),
    ]
