# Generated by Django 4.1.5 on 2023-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_remove_food_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='food/covers/%Y/%m/%d/'),
        ),
    ]
