# Generated by Django 4.1.5 on 2023-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_food_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
